version: '3.9'

services:
  moonlight:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - moonlight-network
    depends_on:
      - db
networks:
  moonlight-network:
    external: true
