version: "3.3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "moon_test"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    #   - ./dump.sql:c:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - moonlight-network
networks:
  moonlight-network:
    external: true
volumes:
  my-db:

