spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/root
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    forward-headers-strategy: framework

  mail:
    host: mail.nasbg.com
    port: 465
    username: "bootcamp@nasbg.com"
    password: '%61%,g]AI,g_'
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

paypal:
  mode: sandbox
  clientId: "AX6Dyi-6lDEba5adpkhXujEvZrEd9YUS4Rwnn7zV9m-qFm_j3lw32Cuv58F7iRmvTvGhXEUlRyStk2q0"
  clientSecret: "EPBocKbwfMbO_lKSdz4txSPbnIQkkLKtANueo3mhACvj_p0uD31EX1OuCz4jn6leG0u5owDzclEACxsD"