name: Deploying

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploying

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true

      - name: Deploy to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/bootcamp-java-23.jar
          remote: apps/bootcamp-java-23.jar
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Reboot the service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: "/usr/bin/env sudo /bin/systemctl restart bootcamp-java-23.service"
